github: [devinschumacher]
open_collective: devinschumacher
custom: [
"https://apps.serp.co/thinkific-downloader",
"https://extensions.serp.co/extensions/serp/thinkific-downloader",
"https://serp.co/products/thinkific-downloader/reviews/",
]
